travis:
  secure:
    BINSTAR_TOKEN: YAQJOB6q6bjKlRR5PS53HY2AvJOyrqzj8dmerIwSgRXWJPKnZxdYNUHhETkySLTAJEaDtAyZMAMEs6r8rSOLdbBVYnR9F6lWJB7YcX2BTehhZqbhI/qjoUYQLQYq0NM4vGfXegw5pR3NTCxoSb82hYZUg4OdO122/Uh3G2QA6B1boLOB+5L4GaQ7o775eNnKP5l1Xt7IB4MbCihuKiXFucyDW7kWeCO0VNRbcybUexlYf6AxUBuL3FXmqlnUvP2BbVI11vZXVN4GtIfiqFxw+pr9dneUSXMY1N2miDIbUMAoEA9zCJhZIM2nBBxOeVxWYia7YOfl9GNN3b0Axq7ygXDNw0nYG0Ph0GtmVLS4tSQPlB1lDr9j+EuS1MoOCkgQrWKqi27rLHjtAoCEMN8VRWkuOt0PCa/9ixdzydPis3hFebKKqCloUuyoxBfwU5/yQ7frCzUgzqXSOqHQ0nI3PYxt4H1nSg/Bi2UDKHqrS/nXN5+5JhZtxM9CMWNQTjIfssk5BHsXOaMXwMLn3qDGKCI8tVbgacaMC3WeN288Twc3pbn9BO/jCxgKDz2z1JsIXfHE5yOwDdPsEY0s/zCsO+494ry8UVS3jtYWnZwOvNTMTTXDQuyCVkrjlikrjJ/K9nyOe1VDpqUN/62J06k10lLmtLDXlqr9yq4sFqlIoTc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
